#!/usr/bin/expect -f
#find / -type f -size 33c -group bandit6 -user bandit7 2>/dev/null -exec cat {} \;
# 2>/dev/null tells all the perm errors to fuck off

spawn ssh bandit6@bandit.labs.overthewire.org -p 2220
expect "assword:"
send "DXjZPULLxYr17uwoI01bNLQbtFemEgo7\r"
interact