#!/usr/bin/expect -f
#The odd bit about this one is uniq only works on ajacent lines
#sort datat.txt | uniq -c -u

spawn ssh bandit8@bandit.labs.overthewire.org -p 2220
expect "assword:"
send "cvX2JJa4CFALtqS87jk27qwqGhBM9plV\r"
interact